### PR TITLE
Tweak

### PR DESCRIPTION
**Pull request by qwertychouskie**

### CODE REVIEW

**Comment by MTres19** [comment]
Thanks. Would you be interested in revamping the kart tutorial in accordance with the [guidelines](https://supertuxkart.net/Maintaining_the_Wiki) I wrote?

**Comment by qwertychouskie** [comment]
Creating/rewriting documentation is not my strong point, though I plan to make some more minor PRs soon.

**Comment by MTres19** [comment]
Let's see proof of that. I think if you put effort into it you'd be able to.

**Comment by qwertychouskie** [comment]
Unfortunately, I am a bit busy, but I have a PR for the FAQ coming soon.

**Pull request merged**
